# Site Settings
title:               lars
tagline:             Architektur- und Landschaftsfotografie
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://lars22.github.io"
author:
  name:              "Lars"
  email:             "weitendorf@outlook.com"
  instagram:         "lars90w"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
