baseURL = "https://lars.22.github.io/"
languageCode = "en-us"
title = "Lars Photoblog"
theme = "hemingway2"
publishDir = "docs"

description = "Your personal description"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[[params.social]]
url = "https://github.com/lars22"
fa_icon = "fa-github"

[[params.social]]
url = "https://github.com/lars22"
fa_icon = "fa-instagram"

[[params.social]]
url = "https://github.com/lars22"
fa_icon = "fa-500px"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
